fix bug
lynxworld/lynx pull request #12
Opened 2021-03-22 07:42 UTC by codeBabyLin

fix bug

2021-03-22 08:37 UTC, bluejoe2008 requested changes

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def orderBy2(df: DataFrame, sortItem: Seq[(Expression, Boolean)])(ctx: ExpressionContext): DataFrame
建议合并到orderBy

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def linSort2(a:Seq[LynxValue], b:Seq[LynxValue])(implicit sitem: Seq[(Expression, Boolean)], schema1: Map[String, (CypherType, Int)], ctx: ExpressionContext): Boolean = {
不要放lin前缀；
这个方法给谁用？就自己用的话改成private

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def groupby(df: DataFrame): DataFrame ={
groupBy
不能直接用orderBy(df: DataFrame, sortItems: Option[Seq[(String, Boolean)]])?
是否private？

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +      /*  if(gBy.isEmpty) DataFrame(df.schema, () => df.records.reduce((a,b) => aggre.map(agg => {
不要放无用代码的注释

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +        def singlel(a: Seq[LynxValue], aggre: mutable.IndexedSeq[(Int, CypherType)]): Seq[LynxValue] ={
single?
是否private?

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +trait DataFrameArray extends DataFrame{
DataFrameArray哪里用？DataFrameArray是一个DataFrame？

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/test/main/scala/org/grapheco/lynx/CypherQueryTest.scala
> +    var rs = runOnDemoGraph("match (n) return  count(n.name),count(n.age)")
原来的orderby测试，就这样被删掉了？

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +        def zero(): Seq[LynxValue] ={
private？

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
> +/*    step match {
大段注释

2021-03-22 08:37 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
> +trait AggregationType{
为每个聚合函数封装一个type是否必要？
是否可以删掉？

2021-03-22 10:38 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def orderBy2(df: DataFrame, sortItem: Seq[(Expression, Boolean)])(ctx: ExpressionContext): DataFrame
已合并

2021-03-22 10:43 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def linSort2(a:Seq[LynxValue], b:Seq[LynxValue])(implicit sitem: Seq[(Expression, Boolean)], schema1: Map[String, (CypherType, Int)], ctx: ExpressionContext): Boolean = {
已经private

2021-03-22 10:43 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  def groupby(df: DataFrame): DataFrame ={
已经private

2021-03-22 10:44 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +      /*  if(gBy.isEmpty) DataFrame(df.schema, () => df.records.reduce((a,b) => aggre.map(agg => {
已经删除

2021-03-22 10:44 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +        def singlel(a: Seq[LynxValue], aggre: mutable.IndexedSeq[(Int, CypherType)]): Seq[LynxValue] ={
不能

2021-03-22 10:45 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +trait DataFrameArray extends DataFrame{
DataFrameArray 已经删除

2021-03-22 10:46 UTC, codeBabyLin commented on lynx-framework/src/test/main/scala/org/grapheco/lynx/CypherQueryTest.scala
> +    var rs = runOnDemoGraph("match (n) return  count(n.name),count(n.age)")
已经加回

2021-03-22 10:46 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +        def zero(): Seq[LynxValue] ={
不能

2021-03-22 10:47 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
> +/*    step match {
已经删除

2021-03-22 10:48 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
> +trait AggregationType{
不能删掉，多个聚合函数可能同时出现，要加以区分

2021-03-22 10:49 UTC, codeBabyLin commented
review的问题已经修复

2021-03-24 07:55 UTC, bluejoe2008 requested changes

2021-03-24 07:55 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  private def groupby(df: DataFrame): DataFrame ={
groupBy
flagOfAggre拼写全了

2021-03-24 07:55 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
>          def singlel(a: Seq[LynxValue], aggre: mutable.IndexedSeq[(Int, CypherType)]): Seq[LynxValue] ={
singlel=>single?

2021-03-24 07:55 UTC, bluejoe2008 commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
>        case f: FunctionInvocation =>
匹配成FunctionInvocation(xxx, FunctionName(name), ...)？
下面直接使用name match{}

2021-03-25 02:05 UTC, closed without merging

2021-03-25 02:15 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
> +  private def groupby(df: DataFrame): DataFrame ={
已拼全

2021-03-25 02:16 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/DataFrame.scala
>          def singlel(a: Seq[LynxValue], aggre: mutable.IndexedSeq[(Int, CypherType)]): Seq[LynxValue] ={
singlel=>single ！

2021-03-25 02:16 UTC, codeBabyLin commented on lynx-framework/src/main/scala/org/grapheco/lynx/eval.scala
>        case f: FunctionInvocation =>
已修改